"""Classify every Python source file in the repo per the rules YAML.

Usage:
    uv run python scripts/audit/classify_files.py            # write report
    uv run python scripts/audit/classify_files.py --check    # exit non-zero on drift

The report lives at ``docs/refactor/file_classification.md``. The
``--check`` mode regenerates the classification in memory and compares
it against the on-disk report; any drift produces a diff and a
non-zero exit code so CI catches files that changed home without
updating the rules.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
RULES_FILE = REPO_ROOT / "scripts" / "audit" / "classification_rules.yaml"
REPORT_FILE = REPO_ROOT / "docs" / "refactor" / "file_classification.md"

VALID_CLASSIFICATIONS = (
    "PROMOTED_CORE",
    "LEGACY_INDIA",
    "REGION_PLUGIN",
    "BROKER_PLUGIN",
    "COMPATIBILITY_SHIM",
)


def _load_rules() -> dict:
    with RULES_FILE.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _excluded(rel: str, excluded: list[str]) -> bool:
    for prefix in excluded:
        if rel.startswith(prefix):
            return True
    return False


def _classify_one(rel: str, rules: list[dict], default: str) -> str:
    for rule in rules:
        if "path" in rule and rule["path"] == rel:
            return rule["classification"]
        if "path_prefix" in rule and rel.startswith(rule["path_prefix"]):
            return rule["classification"]
    return default


def _discover_files(excluded: list[str]) -> list[str]:
    """Walk the repo and yield repo-relative POSIX paths for every .py
    file outside the excluded prefixes and outside __pycache__.

    Uses ``os.walk`` and prunes excluded directories *before* descending,
    so the walker doesn't crawl ``.venv``, ``node_modules``, ``frontend``,
    etc. The naive ``rglob('*.py')`` form took >60 s on this repo.
    """
    import os

    excluded_dirs: set[str] = set()
    for prefix in excluded:
        # excluded entries are path prefixes ending in '/'; treat the
        # leading segment as a directory name to skip at the top level.
        first = prefix.rstrip("/").split("/", 1)[0]
        if first:
            excluded_dirs.add(first)

    files: list[str] = []
    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        rel_dir = Path(dirpath).relative_to(REPO_ROOT).as_posix()
        # Prune excluded subtrees in-place.
        if rel_dir == ".":
            dirnames[:] = [
                d for d in dirnames
                if d not in excluded_dirs and not d.startswith(".") and d != "__pycache__"
            ]
        else:
            dirnames[:] = [d for d in dirnames if d != "__pycache__"]
        for fn in filenames:
            if not fn.endswith(".py"):
                continue
            rel = (Path(rel_dir) / fn).as_posix() if rel_dir != "." else fn
            if _excluded(rel, excluded):
                continue
            files.append(rel)
    return sorted(files)


def classify_all() -> dict[str, list[str]]:
    config = _load_rules()
    rules = config.get("rules") or []
    default = config.get("default", "PROMOTED_CORE")
    excluded = config.get("excluded") or []
    files = _discover_files(excluded)
    bucket: dict[str, list[str]] = defaultdict(list)
    for rel in files:
        cls = _classify_one(rel, rules, default)
        if cls not in VALID_CLASSIFICATIONS:
            raise SystemExit(
                f"Invalid classification {cls!r} for {rel!r}; allowed: "
                f"{VALID_CLASSIFICATIONS}"
            )
        bucket[cls].append(rel)
    return bucket


def render_report(bucket: dict[str, list[str]]) -> str:
    total = sum(len(v) for v in bucket.values())
    lines = [
        "# File classification — market-agnostic v3",
        "",
        "Generated by `scripts/audit/classify_files.py`. Re-run the",
        "classifier after each phase. The check mode",
        "(`uv run python scripts/audit/classify_files.py --check`) exits",
        "non-zero if any file's classification has changed without an",
        "explicit rule update.",
        "",
        f"Total classified files: **{total}**.",
        "",
        "Classification semantics:",
        "",
        "| Bucket | Meaning |",
        "|---|---|",
        "| `PROMOTED_CORE` | Region/broker neutral. Lane-isolation tests run against this list. |",
        "| `LEGACY_INDIA` | India-only, frozen, allowlisted India literals OK. |",
        "| `REGION_PLUGIN` | Under `market_regions/*` — region facts only. |",
        "| `BROKER_PLUGIN` | Under `broker/*` — broker facts only. |",
        "| `COMPATIBILITY_SHIM` | Explicit bridge between lanes (e.g. `domain/translators.py`). |",
        "",
    ]
    for cls in VALID_CLASSIFICATIONS:
        files = bucket.get(cls, [])
        lines.append(f"## {cls} ({len(files)} files)")
        lines.append("")
        if not files:
            lines.append("(none)")
            lines.append("")
            continue
        for rel in files:
            lines.append(f"- `{rel}`")
        lines.append("")
    return "\n".join(lines) + "\n"


def write_report(bucket: dict[str, list[str]]) -> None:
    REPORT_FILE.parent.mkdir(parents=True, exist_ok=True)
    REPORT_FILE.write_text(render_report(bucket), encoding="utf-8")


def parse_report() -> dict[str, list[str]]:
    """Parse the on-disk classification report back into a dict."""
    if not REPORT_FILE.is_file():
        return {}
    text = REPORT_FILE.read_text(encoding="utf-8")
    bucket: dict[str, list[str]] = defaultdict(list)
    current: str | None = None
    for line in text.splitlines():
        if line.startswith("## "):
            head = line[3:].strip()
            for cls in VALID_CLASSIFICATIONS:
                if head.startswith(cls + " ") or head == cls:
                    current = cls
                    break
            else:
                current = None
        elif current and line.startswith("- `") and line.endswith("`"):
            rel = line[3:-1]
            bucket[current].append(rel)
    return bucket


def diff_buckets(a: dict[str, list[str]], b: dict[str, list[str]]) -> list[str]:
    out: list[str] = []
    for cls in VALID_CLASSIFICATIONS:
        a_set = set(a.get(cls, []))
        b_set = set(b.get(cls, []))
        added = sorted(b_set - a_set)
        removed = sorted(a_set - b_set)
        for rel in added:
            out.append(f"+{cls}: {rel}")
        for rel in removed:
            out.append(f"-{cls}: {rel}")
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare current state against on-disk report; exit 1 on drift.",
    )
    args = parser.parse_args()
    bucket = classify_all()
    if args.check:
        on_disk = parse_report()
        if not on_disk:
            print(
                "Classification report missing at "
                f"{REPORT_FILE}. Run without --check to generate it.",
                file=sys.stderr,
            )
            return 1
        diffs = diff_buckets(on_disk, bucket)
        if diffs:
            print(
                "Classification drift detected. Either update the rules "
                "or relocate the offending files.",
                file=sys.stderr,
            )
            for line in diffs:
                print(f"  {line}", file=sys.stderr)
            return 1
        print(f"OK: {sum(len(v) for v in bucket.values())} files classified, no drift.")
        return 0
    write_report(bucket)
    print(f"Wrote {REPORT_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
