"""Phase 3 v3 — audit every reader of ``database.symbol`` /
``database.token_db_enhanced`` and classify each caller.

Output: ``docs/refactor/symtoken_callers.md`` — Markdown grouped by
classification:

* ``LEGACY_INDIA``   — expected and allowed.
* ``PROMOTED_LEAK``  — must be fixed in this phase or before.
* ``BROKER_PLUGIN``  — broker adapter; should use broker-specific
  symbol/token map (broker_instrument_map) instead of SymToken.
* ``SHIM``           — named compatibility bridge with a TODO.
* ``UNCLASSIFIED``   — file is not in the classification report;
  shouldn't happen if Phase 0's classifier ran.

Reads the Phase 0 file_classification.md report so the same source of
truth drives both the SymToken audit and the lane-isolation
contracts.
"""

from __future__ import annotations

import ast
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CLASSIFICATION_REPORT = REPO_ROOT / "docs" / "refactor" / "file_classification.md"
OUTPUT = REPO_ROOT / "docs" / "refactor" / "symtoken_callers.md"

LEGACY_MODULES = ("database.symbol", "database.token_db_enhanced")


def _load_classification() -> dict[str, str]:
    """Return a dict mapping repo-relative POSIX path -> bucket name."""
    if not CLASSIFICATION_REPORT.is_file():
        return {}
    text = CLASSIFICATION_REPORT.read_text(encoding="utf-8")
    out: dict[str, str] = {}
    current: str | None = None
    for line in text.splitlines():
        if line.startswith("## "):
            head = line[3:].strip()
            current = head.split(" ", 1)[0]
        elif current and line.startswith("- `") and line.endswith("`"):
            out[line[3:-1]] = current
    return out


def _module_imports(path: Path) -> set[str]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, SyntaxError):
        return set()
    mods: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                mods.add(alias.name)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                mods.add(node.module)
    return mods


_EXCLUDED_TOP_DIRS: frozenset[str] = frozenset(
    {
        ".venv",
        "node_modules",
        "frontend",
        "tests",
        "test",
        "docs",
        "examples",
        "collections",
        "install",
        "upgrade",
        "audit",
        "data",
        "db",
        "download",
        "keys",
        "log",
        "tmp",
        "openalgoUI.egg-info",
        "events",
        "subscribers",
        "strategies",
        "scripts",
    }
)


def _walk_source_files() -> list[Path]:
    """Walk the repo with `os.walk` and prune excluded subtrees before
    descending — `rglob('*.py')` takes >60 s on this repo because it
    walks `.venv` and `node_modules` first.
    """
    import os

    out: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        rel_dir = Path(dirpath).relative_to(REPO_ROOT).as_posix()
        if rel_dir == ".":
            dirnames[:] = [
                d for d in dirnames
                if d not in _EXCLUDED_TOP_DIRS
                and not d.startswith(".")
                and d != "__pycache__"
            ]
        else:
            dirnames[:] = [d for d in dirnames if d != "__pycache__"]
        for fn in filenames:
            if not fn.endswith(".py"):
                continue
            out.append(Path(dirpath) / fn)
    return out


def audit() -> tuple[dict[str, list[tuple[str, list[str]]]], dict[str, str]]:
    """Return (bucket -> [(rel, [legacy_modules_imported])], classification)."""
    classification = _load_classification()
    bucket: dict[str, list[tuple[str, list[str]]]] = defaultdict(list)
    for path in _walk_source_files():
        rel = path.relative_to(REPO_ROOT).as_posix()
        imports = _module_imports(path)
        hits = sorted(
            mod
            for mod in imports
            if any(mod == legacy or mod.startswith(legacy + ".") for legacy in LEGACY_MODULES)
        )
        if not hits:
            continue
        cls = classification.get(rel, "UNCLASSIFIED")
        if cls == "PROMOTED_CORE":
            bucket["PROMOTED_LEAK"].append((rel, hits))
        else:
            bucket[cls].append((rel, hits))
    return bucket, classification


def render(bucket: dict[str, list[tuple[str, list[str]]]]) -> str:
    out = [
        "# SymToken caller audit",
        "",
        "Generated by `scripts/audit/symtoken_callers.py`. Each entry",
        "names a file that imports from `database.symbol` or",
        "`database.token_db_enhanced` at module-load time, classified",
        "by the Phase 0 file_classification report.",
        "",
        "* `LEGACY_INDIA` — expected and allowed.",
        "* `PROMOTED_LEAK` — must be fixed; PROMOTED_CORE files cannot",
        "  depend on SymToken.",
        "* `BROKER_PLUGIN` — broker adapter; should use a",
        "  broker-specific lookup against `broker_instrument_map`.",
        "* `COMPATIBILITY_SHIM` — sanctioned bridge.",
        "* `UNCLASSIFIED` — file not in the classification report.",
        "",
    ]
    total = sum(len(v) for v in bucket.values())
    out.append(f"Total caller files: **{total}**.")
    out.append("")

    order = [
        "PROMOTED_LEAK",
        "COMPATIBILITY_SHIM",
        "BROKER_PLUGIN",
        "LEGACY_INDIA",
        "UNCLASSIFIED",
    ]
    for bk in order:
        files = sorted(bucket.get(bk, []))
        out.append(f"## {bk} ({len(files)} files)")
        out.append("")
        if not files:
            out.append("(none)")
            out.append("")
            continue
        for rel, hits in files:
            out.append(f"- `{rel}` — imports: {', '.join(hits)}")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    bucket, classification = audit()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(bucket), encoding="utf-8")
    leaks = bucket.get("PROMOTED_LEAK", [])
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    print(f"PROMOTED_LEAK entries: {len(leaks)}")
    return 0 if not leaks else 1


if __name__ == "__main__":
    raise SystemExit(main())
