#!/usr/bin/env python3
"""Render `docs/refactor/broker_compliance_matrix.md` from the
results recorded by the compliance harness.

Run after the compliance suite::

    uv run pytest tests/compliance/
    uv run python tests/compliance/render_matrix.py

The matrix renderer is a separate script (not a fixture) because it
needs to inspect the in-process module state populated during the
test run. To support running it independently, this script re-imports
the harness module to read its global ``COMPLIANCE_RESULTS`` and then
re-runs pytest under the hood when invoked alone.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUT = REPO_ROOT / "docs" / "refactor" / "broker_compliance_matrix.md"

CONTRACTS = [
    "metadata",
    "auth",
    "account",
    "translator",
    "market_data",
    "instrument_sync",
    "rules",
    "lane_isolation",
    "fail_closed",
]


def main() -> int:
    # Run the compliance suite under pytest and collect the results in-process.
    # We exec pytest in-process so COMPLIANCE_RESULTS is populated.
    sys.path.insert(0, str(REPO_ROOT))
    os.chdir(REPO_ROOT)

    # Run the harness via pytest's main so it populates COMPLIANCE_RESULTS.
    import pytest

    pytest.main(["tests/compliance/", "-q", "--no-header"])

    from tests.compliance.broker_plugin_compliance import COMPLIANCE_RESULTS

    if not COMPLIANCE_RESULTS:
        print("No compliance results captured.", file=sys.stderr)
        return 1

    rows = []
    for broker_code in sorted(COMPLIANCE_RESULTS):
        results = COMPLIANCE_RESULTS[broker_code]
        cells = []
        for contract in CONTRACTS:
            v = results.get(contract, "skip")
            if v == "pass":
                cells.append("✅")
            elif v == "skip":
                cells.append("skip")
            elif v.startswith("fail"):
                cells.append("❌ " + v.split(":", 1)[1] if ":" in v else "❌")
            else:
                cells.append(v)
        rows.append("| " + broker_code + " | " + " | ".join(cells) + " |")

    header = "| Broker | " + " | ".join(c.replace("_", " ").title() for c in CONTRACTS) + " |"
    sep = "|---|" + "|".join(["---"] * len(CONTRACTS)) + "|"
    body = "\n".join([header, sep] + rows)

    OUT.write_text(
        f"""# Broker Plugin Compliance Matrix

Auto-generated by `tests/compliance/render_matrix.py`. Re-run after
each compliance test pass.

{body}

## Legend

* ✅ pass
* ❌ fail (reason after)
* skip — not applicable to this broker (legacy lane / not yet implemented)

See `docs/adr/0012-broker-plugin-compliance-harness.md` for the
contract details.
""",
        encoding="utf-8",
    )
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
