"""Authenticated /api/v1 + /api/v2 surface sweep.

Reads session cookie from tests/e2e_smoke/_artifacts/cookies.txt
(generated by smoke_login_and_sweep.mjs) and walks the documented API
surface. Records pass/fail per endpoint into _artifacts/api_results.json.

Read-only first (GET endpoints). Order placement / cancellation are NOT
exercised here — the strategy script's tests cover those via mocks; live
order traffic is gated by the broker's market hours and we honor the
"market closed" caveat from the operator.
"""
from __future__ import annotations

import json
import os
import sys
import time
from http.cookiejar import MozillaCookieJar
from pathlib import Path
from typing import Any

import httpx

ROOT = Path(__file__).resolve().parents[2]
ART = ROOT / "tests" / "e2e_smoke" / "_artifacts"
COOKIES = ART / "cookies.txt"
RESULTS = ART / "api_results.json"

BASE = os.environ.get("HOST_SERVER", "http://127.0.0.1:5000").rstrip("/")
API_KEY = os.environ.get("OPENALGO_API_KEY") or ""


def load_cookies() -> dict[str, str]:
    jar = MozillaCookieJar(str(COOKIES))
    jar.load(ignore_discard=True, ignore_expires=True)
    return {c.name: c.value for c in jar}


def fmt(payload: Any, n: int = 240) -> str:
    s = json.dumps(payload, default=str)
    return s if len(s) <= n else s[:n] + "..."


def call(client: httpx.Client, method: str, path: str, *,
         params: dict | None = None, json_body: dict | None = None,
         expect: int | tuple[int, ...] = 200) -> dict[str, Any]:
    url = path if path.startswith("http") else f"{BASE}{path}"
    started = time.perf_counter()
    try:
        r = client.request(
            method, url,
            params=params or None,
            json=json_body if json_body is not None else None,
            timeout=20.0,
        )
        elapsed = (time.perf_counter() - started) * 1000
        body: Any
        try:
            body = r.json()
        except Exception:
            body = r.text[:200]
        ok_codes = (expect,) if isinstance(expect, int) else expect
        passed = r.status_code in ok_codes
        result = {
            "method": method, "path": path,
            "status": r.status_code, "ms": round(elapsed, 1),
            "passed": passed, "expected": list(ok_codes),
            "body_preview": fmt(body),
        }
        # Carry through structured error code so triage is fast.
        if isinstance(body, dict) and isinstance(body.get("error"), dict):
            result["error_code"] = body["error"].get("code")
        print(f"  {method:6s} {path:60s} -> {r.status_code} ({result['ms']:.0f}ms) "
              f"{'OK' if passed else 'FAIL'}")
        return result
    except Exception as e:
        elapsed = (time.perf_counter() - started) * 1000
        print(f"  {method:6s} {path:60s} -> EXC {e!s:.80}")
        return {"method": method, "path": path, "status": None,
                "ms": round(elapsed, 1), "passed": False, "exception": str(e)}


def main() -> int:
    if not COOKIES.exists():
        print(f"missing {COOKIES}; run smoke_login_and_sweep.mjs first")
        return 2
    cookies = load_cookies()
    print(f"[api] loaded {len(cookies)} cookies")
    print(f"[api] BASE={BASE}")

    client = httpx.Client(cookies=cookies, follow_redirects=False)
    results: list[dict] = []

    # ----- internal session-auth UI APIs (cookie-based) -----
    print("\n--- /auth/* ---")
    results += [
        call(client, "GET", "/auth/csrf-token"),
        call(client, "GET", "/auth/session"),
        call(client, "GET", "/auth/brokers"),
        call(client, "GET", "/auth/check-setup"),
    ]

    # Master contract status + cache health (session-auth)
    print("\n--- /api/master-contract + /api/cache ---")
    results += [
        call(client, "GET", "/api/master-contract/status"),
        call(client, "GET", "/api/master-contract/ready"),
        call(client, "GET", "/api/master-contract/smart-status"),
        call(client, "GET", "/api/cache/status"),
        call(client, "GET", "/api/cache/health"),
    ]

    # ----- /api/v2 lane (session OR API key — try session first) -----
    print("\n--- /api/v2 (regions / venues) ---")
    results += [
        call(client, "GET", "/api/v2/regions"),
        call(client, "GET", "/api/v2/regions/india"),
        call(client, "GET", "/api/v2/regions/us"),
        call(client, "GET", "/api/v2/regions/eu"),
        call(client, "GET", "/api/v2/regions/uk"),
        call(client, "GET", "/api/v2/regions/india/flow_defaults"),
        call(client, "GET", "/api/v2/regions/us/flow_defaults"),
        call(client, "GET", "/api/v2/venues"),
        call(client, "GET", "/api/v2/venues/XNAS"),
        call(client, "GET", "/api/v2/venues/CRYPTO"),
        call(client, "GET", "/api/v2/venues/XNAS/sessions",
             params={"date": "2026-05-06"}),
    ]

    # /api/v2 promoted lane endpoints (require resolve_auth — usually API key)
    print("\n--- /api/v2 promoted lane (Alpaca) ---")
    if API_KEY:
        # API-key-authenticated body (apikey in body for POST, query for GET).
        results += [
            call(client, "GET", "/api/v2/balances", params={"apikey": API_KEY}),
            call(client, "GET", "/api/v2/positions", params={"apikey": API_KEY}),
            call(client, "GET", "/api/v2/orders",
                 params={"apikey": API_KEY, "status": "open"}),
            call(client, "GET", "/api/v2/orders",
                 params={"apikey": API_KEY, "status": "all"}),
        ]
        # Quote/Bar require POST with instrument body.
        results.append(call(
            client, "POST", "/api/v2/quotes",
            json_body={
                "apikey": API_KEY,
                "instruments": [{"venue_code": "XNAS", "canonical_symbol": "AAPL"}],
            },
        ))
        results.append(call(
            client, "POST", "/api/v2/bars",
            json_body={
                "apikey": API_KEY,
                "instrument": {"venue_code": "XNAS", "canonical_symbol": "AAPL"},
                "interval": "1d",
                "start": "2026-04-01T00:00:00Z",
                "end": "2026-05-06T00:00:00Z",
            },
        ))
    else:
        print("  OPENALGO_API_KEY not set in env — skipping promoted-lane authenticated calls.")

    # ----- /api/v1 lane (legacy, india-shape) -----
    print("\n--- /api/v1 (legacy lane via Alpaca compat) ---")
    if API_KEY:
        # These endpoints exist on Alpaca's compat shim; should return 200
        # with India-shaped legacy bodies even though broker is Alpaca.
        for path, body in [
            ("/api/v1/funds", {"apikey": API_KEY}),
            ("/api/v1/positionbook", {"apikey": API_KEY}),
            ("/api/v1/orderbook", {"apikey": API_KEY}),
            ("/api/v1/holdings", {"apikey": API_KEY}),
            ("/api/v1/tradebook", {"apikey": API_KEY}),
        ]:
            results.append(call(client, "POST", path, json_body=body))
        # quotes / depth (read-only data API)
        results.append(call(
            client, "POST", "/api/v1/quotes",
            json_body={"apikey": API_KEY, "symbol": "AAPL", "exchange": "NSE"},
            expect=(200, 400, 404, 422),  # likely 404/422 — Alpaca symbol AAPL on NSE makes no sense
        ))
        # ping / version
        for path in ["/api/v1/ping", "/api/v1/version"]:
            results.append(call(client, "GET", path,
                                expect=(200, 404, 405)))
    else:
        print("  OPENALGO_API_KEY not set — skipping /api/v1 authenticated calls")

    # ----- summary -----
    passed = sum(1 for r in results if r.get("passed"))
    total = len(results)
    print(f"\n[summary] {passed}/{total} passed")

    failures = [r for r in results if not r.get("passed")]
    if failures:
        print("\n--- failures ---")
        for r in failures:
            print(f"  {r['method']} {r['path']:55s} status={r.get('status')} "
                  f"err={r.get('error_code') or r.get('exception','')[:60]} "
                  f"body={r.get('body_preview','')[:140]}")

    RESULTS.write_text(json.dumps({
        "base": BASE, "passed": passed, "total": total,
        "results": results,
    }, indent=2, default=str))
    print(f"\n[done] -> {RESULTS}")
    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
