// Headless browser smoke sweep for OpenAlgo.
//
// 1. Logs in via the web UI using web_login_username / web_login_password.
// 2. Visits the major React pages and captures any console / network
//    errors per page.
// 3. Saves the storage state (cookies + localStorage) so the API sweep
//    can reuse the session.
//
// Output:
//   tests/e2e_smoke/_artifacts/storage.json    — Playwright storage state
//   tests/e2e_smoke/_artifacts/cookies.txt     — curl-compatible Netscape jar
//   tests/e2e_smoke/_artifacts/results.json    — per-page status
//
// Usage: node tests/e2e_smoke/smoke_login_and_sweep.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { chromium } from "playwright";
import { config as loadEnv } from "dotenv";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");
loadEnv({ path: path.join(REPO_ROOT, ".env") });

const BASE = process.env.HOST_SERVER?.replace(/\/$/, "") || "http://127.0.0.1:5000";
const USER = process.env.web_login_username || process.env.WEB_LOGIN_USERNAME;
const PASS = process.env.web_login_password || process.env.WEB_LOGIN_PASSWORD;
if (!USER || !PASS) {
  console.error("Missing web_login_username / web_login_password in .env");
  process.exit(2);
}

const ARTIFACTS = path.join(__dirname, "_artifacts");
fs.mkdirSync(ARTIFACTS, { recursive: true });

const PAGES = [
  { name: "root", path: "/" },
  { name: "dashboard", path: "/dashboard" },
  { name: "react", path: "/react" },
  { name: "react-dashboard", path: "/react/#/dashboard" },
  { name: "orderbook", path: "/orderbook" },
  { name: "tradebook", path: "/tradebook" },
  { name: "positions", path: "/positions" },
  { name: "holdings", path: "/holdings" },
  { name: "funds", path: "/funds" },
  { name: "search", path: "/search" },
  { name: "apikey", path: "/apikey" },
  { name: "logs", path: "/logs" },
  { name: "analyzer", path: "/analyzer" },
  { name: "master_contract", path: "/master_contract" },
  { name: "settings", path: "/settings" },
  { name: "api-docs", path: "/api/docs" },
];

function dumpCookiesNetscape(cookies, outPath) {
  // Standard Netscape jar format curl accepts via -b
  const lines = ["# Netscape HTTP Cookie File", "# Generated by smoke sweep"];
  for (const c of cookies) {
    const expires = c.expires && c.expires > 0 ? Math.floor(c.expires) : 0;
    const domain = c.domain.startsWith(".") ? c.domain : c.domain;
    const flag = c.domain.startsWith(".") ? "TRUE" : "FALSE";
    const secure = c.secure ? "TRUE" : "FALSE";
    lines.push([
      domain,
      flag,
      c.path || "/",
      secure,
      expires,
      c.name,
      c.value,
    ].join("\t"));
  }
  fs.writeFileSync(outPath, lines.join("\n") + "\n");
}

async function main() {
  const browser = await chromium.launch({ headless: true });
  const ctx = await browser.newContext({ baseURL: BASE });
  const page = await ctx.newPage();

  const consoleErrors = [];
  const pageErrors = [];
  const failedRequests = [];
  page.on("console", (msg) => {
    if (msg.type() === "error") consoleErrors.push({ url: page.url(), text: msg.text() });
  });
  page.on("pageerror", (err) => {
    pageErrors.push({ url: page.url(), text: err.message });
  });
  page.on("requestfailed", (req) => {
    failedRequests.push({ url: req.url(), method: req.method(), failure: req.failure()?.errorText });
  });

  console.log(`[login] navigating ${BASE}/login`);
  await page.goto("/login", { waitUntil: "domcontentloaded" });

  // Login form selectors — username + password inputs are conventional.
  const userField = await page.$("input[name='username'], input[id*='user' i], input[type='text']");
  const passField = await page.$("input[name='password'], input[id*='pass' i], input[type='password']");
  if (!userField || !passField) {
    console.error("[login] could not locate login form fields");
    await page.screenshot({ path: path.join(ARTIFACTS, "login_missing_fields.png"), fullPage: true });
    process.exit(3);
  }
  await userField.fill(USER);
  await passField.fill(PASS);

  const submit = await page.$("button[type='submit'], input[type='submit'], button:has-text('Login'), button:has-text('Sign in')");
  if (!submit) {
    console.error("[login] could not locate submit button");
    process.exit(4);
  }
  await Promise.all([
    page.waitForLoadState("networkidle", { timeout: 15000 }).catch(() => {}),
    submit.click(),
  ]);

  const postLoginUrl = page.url();
  console.log(`[login] post-login URL: ${postLoginUrl}`);
  await page.screenshot({ path: path.join(ARTIFACTS, "post_login.png"), fullPage: true });

  if (/\/login/.test(postLoginUrl)) {
    const errBanner = await page.$(".alert, .toast, [role='alert']");
    const msg = errBanner ? await errBanner.innerText() : "(no banner)";
    console.error(`[login] still on /login — failed. Banner: ${msg}`);
    process.exit(5);
  }

  // Persist storage state for any subsequent Playwright runs.
  await ctx.storageState({ path: path.join(ARTIFACTS, "storage.json") });
  // Also dump cookies for curl-based API sweeps.
  const cookies = await ctx.cookies();
  dumpCookiesNetscape(cookies, path.join(ARTIFACTS, "cookies.txt"));
  console.log(`[login] saved ${cookies.length} cookies`);

  // Page sweep.
  const results = [];
  for (const target of PAGES) {
    const before = consoleErrors.length;
    const beforeP = pageErrors.length;
    const beforeF = failedRequests.length;
    try {
      const resp = await page.goto(target.path, {
        waitUntil: "domcontentloaded", timeout: 20000,
      });
      // Let SPA settle.
      await page.waitForLoadState("networkidle", { timeout: 8000 }).catch(() => {});
      const status = resp ? resp.status() : null;
      const url = page.url();
      const ts = new Date().toISOString().replace(/[:.]/g, "-");
      const shotPath = path.join(ARTIFACTS, `${target.name}.png`);
      await page.screenshot({ path: shotPath, fullPage: true }).catch(() => {});
      results.push({
        page: target.name,
        path: target.path,
        status,
        final_url: url,
        new_console_errors: consoleErrors.slice(before),
        new_page_errors: pageErrors.slice(beforeP),
        new_failed_requests: failedRequests.slice(beforeF),
        screenshot: path.basename(shotPath),
      });
      console.log(`[sweep] ${target.path} -> ${status} (${url})`);
    } catch (e) {
      console.error(`[sweep] ${target.path} -> error: ${e.message}`);
      results.push({
        page: target.name, path: target.path,
        status: null, error: e.message,
      });
    }
  }

  fs.writeFileSync(
    path.join(ARTIFACTS, "results.json"),
    JSON.stringify(
      {
        base: BASE,
        username: USER,
        results,
        all_console_errors: consoleErrors,
        all_page_errors: pageErrors,
        all_failed_requests: failedRequests,
      },
      null, 2,
    ),
  );

  console.log(`[done] results -> ${path.join(ARTIFACTS, "results.json")}`);
  await browser.close();
}

main().catch((e) => {
  console.error("FATAL", e);
  process.exit(1);
});
