"""GET /api/v2/admin/broker_compliance — broker compliance matrix.

Returns the contract matrix the Phase 7 compliance harness produces,
serialized for an admin Settings panel page. Reads the matrix file
generated by `tests/compliance/render_matrix.py`. Falls back to an
empty matrix when the file is missing (fresh install before the
harness has been run).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from flask_restx import Namespace, Resource

from restx_api.v2._auth import error, ok

api = Namespace(
    "broker_compliance",
    description="Broker plugin compliance matrix (admin)",
)

REPO_ROOT = Path(__file__).resolve().parents[2]
MATRIX_PATH = REPO_ROOT / "docs" / "refactor" / "broker_compliance_matrix.md"


def _parse_matrix(md: str) -> list[dict[str, Any]]:
    """Best-effort markdown table → list of {broker, contracts: {...}}.

    The renderer writes a fixed header; we extract the contract names
    from the first row and broker results from each row beneath.
    """
    lines = [
        ln.strip()
        for ln in md.splitlines()
        if ln.strip().startswith("|") and ln.strip().endswith("|")
    ]
    if len(lines) < 3:
        return []
    header_cells = [c.strip() for c in lines[0].strip("|").split("|")]
    # First column is "Broker"; rest are contract names.
    contract_names = [c.lower().replace(" ", "_") for c in header_cells[1:]]
    rows: list[dict[str, Any]] = []
    for ln in lines[2:]:
        cells = [c.strip() for c in ln.strip("|").split("|")]
        if len(cells) != len(header_cells):
            continue
        broker_cell = cells[0]
        broker = re.sub(r"\*+", "", broker_cell).strip()
        contracts: dict[str, str] = {}
        for name, value in zip(contract_names, cells[1:]):
            v = value
            if v.startswith("✅"):
                contracts[name] = "pass"
            elif v.startswith("❌"):
                contracts[name] = "fail"
            elif v.lower().startswith("skip"):
                contracts[name] = "skip"
            else:
                contracts[name] = v
        rows.append({"broker": broker, "contracts": contracts})
    return rows


@api.route("")
@api.route("/")
class BrokerCompliance(Resource):
    def get(self):
        if not MATRIX_PATH.is_file():
            return ok({
                "matrix": [],
                "source": str(MATRIX_PATH.relative_to(REPO_ROOT)),
                "message": "compliance matrix not generated yet",
            }), 200
        try:
            md = MATRIX_PATH.read_text(encoding="utf-8")
        except OSError as e:
            return error("internal_error", f"could not read matrix: {e}"), 500
        return ok({
            "matrix": _parse_matrix(md),
            "source": str(MATRIX_PATH.relative_to(REPO_ROOT)),
        }), 200
